services:
  tgraph-bot:
    build: https://github.com/engels74/tgraph-bot-source.git
    image: tgraph-bot:latest
    container_name: tgraph-bot
    environment:
      - TAUTULLI_API_KEY=your_tautulli_api_key
      - TAUTULLI_URL=http://your_tautulli_ip:port/api/v2
      - DISCORD_TOKEN=your_discord_bot_token
      - CHANNEL_ID=your_channel_id
      - UPDATE_DAYS=7
      - IMG_FOLDER=img
      - KEEP_DAYS=7
      - TIME_RANGE_DAYS=30
      - TZ=Etc/UTC
    volumes:
      - ./logs:/logs
      - ./img:/app/img
    restart: unless-stopped
